name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: windows-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
         java-version: 11
         distribution: temurin
         architecture: x64      
    - name: HuffCompTests
      id: huffcomptests
      uses: education/autograding-command-grader@v1
      with:
        test-name: HuffCompTests
        setup-command: ''
        command: gradle test --tests "HF_*"
        timeout: 5
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        HUFFCOMPTESTS_RESULTS: "${{steps.huffcomptests.outputs.result}}"
      with:
        runners: huffcomptests
